site_name: COMP2825
site_url: https://gdoyle87.github.io/COMP2825/
nav:
  - Home: index.md
  - Week 1 - Overview of Computer Architecture: wk_one.md
  - Other Notes: https://gdoyle87.github.io/

theme: readthedocs
markdown_extensions:
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.js

extra_css:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.css
